---
- name: Deploy Dockerized Application
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      update_cache: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image
      docker_image:
        name: my-app
        source: pull

    - name: Run the Docker container
      docker_container:
        name: my-app-container
        image: my-app
        state: started
        ports:
          - "5173:5173"
